version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20
  slack: circleci/slack@4.9.3

jobs:
  python-with-sonar-scanner:
    docker:
      - image: circleci/python:3.7.3
    environment:
      - JAVA_REPOSITORY: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.13_8.tar.gz
      - JAVA_VERSION: 11.0.13
    working_directory: ~/app
    steps:
      - run:
          name: Check Python version (before)
          command: python --version
      - run:
          name: Install OpenJDK 11
          command: |
              sudo curl -sSL -o java.tar.gz "${JAVA_REPOSITORY}"
              sudo mkdir /usr/local/jdk-${JAVA_VERSION}
              sudo tar -xzf java.tar.gz --strip-components=1 -C /usr/local/jdk-${JAVA_VERSION}
              sudo rm java.tar.gz

              if [[ "$JAVA_VERSION" == *"0.0"* ]]; then \
                sudo ln -s /usr/local/jdk-${JAVA_VERSION} /usr/local/jdk-11; \
              fi
              sudo ln -s /usr/local/jdk-${JAVA_VERSION}/bin/java /usr/bin/java
              sudo ln -s /usr/local/jdk-${JAVA_VERSION}/bin/javac /usr/bin/javac
              sudo ln -s /usr/local/jdk-${JAVA_VERSION}/bin/javaws /usr/bin/javaws
              export PATH="$PATH:/usr/local/jdk-${JAVA_VERSION}"
              export JAVA_HOME="/usr/local/jdk-${JAVA_VERSION}"

              java --version
      - run:
          name: Install SonarQube scanner
          command: |
            sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            sudo unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - run:
          name: Run SonarQube scanner
          command: |
            export PATH="$PATH:/usr/local/jdk-${JAVA_VERSION}"
            export JAVA_HOME="/usr/local/jdk-${JAVA_VERSION}"
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            ls -al sonar-scanner-cli-4.7.0.2747-linux/bin/
      - run:
          name: Check Python version (after)
          command: python --version

workflows:
  version: 2

  test-workflow:
    jobs:
      - python-with-sonar-scanner:
          filters:
            branches:
              only: master
